name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  armv7_job:
    runs-on: ubuntu-20.04
    name: Build on ARMv7 
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: armv6
          distribution: buster
          run: go build -v .
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"


  
