name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  armv6_job:
    runs-on: ubuntu-20.04
    name: Build on ARMv6
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: armv6
          distribution: buster
          run: |
            apt update
            apt install wget build-essential
            wget https://storage.googleapis.com/golang/go1.14.linux-armv6l.tar.gz
            tar -C /usr/local -xzf go1.14.linux-armv6l.tar.gz
            /usr/local/go/bin/go get -v . 
            /usr/local/go/bin/go build -v . 
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: climate-metrics-armv6
          path: climate-metrics
  #armv7_job:
  #  runs-on: ubuntu-20.04
  #  name: Build on ARMv7 
  #  steps:
  #    - uses: actions/checkout@v2.1.0
  #    - uses: uraimo/run-on-arch-action@v1.0.9
  #      id: runcmd
  #      with:
  #        architecture: armv7
  #        distribution: buster
  #        run: |
  #          apt update
  #          apt install wget build-essential
  #          wget https://storage.googleapis.com/golang/go1.14.linux-armv7l.tar.gz
  #          tar -C /usr/local -xzf go1.14.linux-armv7l.tar.gz
  #          /usr/local/go/bin/go get -v . 
  #          /usr/local/go/bin/go build -v . 
  #    - name: Upload artifact
  #      uses: actions/upload-artifact@master
  #      with:
  #        name: climate-metrics-armv7
  #        path: climate-metrics
  release:
    runs-on: ubuntu-latest
    needs: [armv6_job] # armv7_job
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: climate-metrics-armv6
        path: v6
#    - uses: actions/download-artifact@v2
#      with:
#        name: climate-metrics-armv7
#        path: v7
    - name: List details
      run: |
        ls -lisa
        ls -lisa v6
        mv v6/climate-metrics climate-metrics-armv6
        ls -lisa
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Creates a draft release. Defaults to false
        draft: true
        # Identify the release as a prerelease. Defaults to false
        prerelease: true
        # Newline-delimited list of path globs for asset files to upload
        files: |
          climate-metrics-armv6
#          climate-metrics-armv7
